name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: regd1.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker build ./backend -t regd1.azurecr.io/my-backend:${{ github.sha }}
          docker push regd1.azurecr.io/my-backend:${{ github.sha }}

      - name: Build and Push Frontend
